services:
  - type: web
    name: bookmyslot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DATABASE_URL
        fromDatabase:
          name: bookmyslot-db
          property: connectionString

databases:
  - name: bookmyslot-db
    databaseName: bookmyslot_db
    user: bookmyslot_user 